[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "_build",
    "venv",
]

[tool.ruff.lint]
ignore = ["F821"]

[tool.pyright]
venvPath = "."
venv = ".venv"
